title: "KhasiDRP"
email: udaycruise2903@gmail.com
timezone: IST
baseurl: "/khasidrp"
permalink: "/:title/"
logo: 'images/logo.png'
favicon: 'images/favicon.ico'
author: 
paginate: 30
disqus: ''
locale: en_in
lang: en_us
feed_items: 12
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:  



# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
